apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-uios
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-uios
    app.kubernetes.io/part-of: hacbs-demo-test-app-ipqb
  name: test-component-uios
  namespace: hacbs-e2e-tgkw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-uios
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-uios
    spec:
      containers:
      - image: quay.io/psturc/test-images@sha256:11c2f5c1f328b7cf9d861f52aac0e31a8b2739fc251e7a22f9baeb7c2460e094
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
