apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-uios
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-uios
    app.kubernetes.io/part-of: hacbs-demo-test-app-ipqb
  name: test-component-uios
  namespace: hacbs-e2e-tgkw
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-component-uios
    weight: 100
status: {}
